### ISSUE TITLE
Client Registry Timeout of 5 seconds Too Low

### ISSUE THREAD

**Issue by sasial-dev** [paradoxuum/centurion#43]
For clients with slower connections or even starting a local test server in studio, the timeout of 5 seconds on the client registry is too low.

https://github.com/paradoxuum/centurion/blob/main/packages/core/src/client/registry.ts#L76

Either we can:
- Increase the timeout limit
- Remove the limit all together

I'm curious to know what type of option you'd like to take.

**Comment by paradoxuum** [comment]
I'd like to keep the limit and make it configurable ideally. I think for slower connections it's probably not as big of a deal since they'll eventually be kicked from the server anyway if they're not able to connect for long enough. I didn't know this was an issue with local test servers though, so the best option is to probably make it configurable and increase the default timeout.
